[package]
name = "mr_house"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
once_cell = "1.21.3"
poise = "0.6.1"
rand = "0.9.1"
serenity = "0.12.4"
tokio = "1.45.1"
tracing = "0.1.41"

[build-dependencies]
built = { version = "0.8.0", features = ["chrono", "dependency-tree"] }
